### PR TITLE
Add v1 and v2 buckets to the docs, make changes to v2 docs and update…

### PR DESCRIPTION
**Pull request by kcurtin**
… intro in v1

### CODE REVIEW

**Comment by kcurtin** [comment]
@briancantrell FYI - this seems to work pretty well - i created new directories for v1 and v2 and they each have their own index.html file. I think we may be able to up date the rules in the s3 static hosting and will be all set. _think_ - also, can you take a pass through the changes to make sure i got them all?

Still need to figure out if I am going to remove some behavior from the docs..

**Comment by kcurtin** [comment]
also need links to the old and new one

**Comment by kcurtin** [comment]
just remembered we talked about serving the most up to date version from the root. that actually makes more sense so we don't have to update the links sales and co. send out

**Comment by briancantrell** [comment]
Awesome, I will check out your changes, move the current version to root and add a link to the old one.

**Comment by kcurtin** [comment]
decided on a simpler solution: https://github.com/contently/slate/pull/8

**Pull request closed without merging**
